

def get_base_item_types():
    return [
        "Plate Vest",
"Iron Greaves",
"Crude Bow",
"Glass Shank",
"Iron Gauntlets",
"Iron Hat",
"Small Life Flask",
"Small Mana Flask",
"Driftwood Club",
"Rusted Sword",
"Driftwood Sceptre",
"Splintered Tower Shield",
"Driftwood Wand",
"Chain Belt",
"Rustic Sash",
"Shabby Jerkin",
"Rusted Hatchet",
"Iron Ring",
"Goathide Buckler",
"Paua Amulet",
"Coral Amulet",
"Simple Robe",
"Wool Shoes",
"Rawhide Boots",
"Nailed Fist",
"Wool Gloves",
"Rawhide Gloves",
"Vine Circlet",
"Leather Cap",
"Medium Life Flask",
"Medium Mana Flask",
"Twig Spirit Shield",
"Rusted Spike",
"Driftwood Maul",
"Corroded Blade",
"Scale Vest",
"Chainmail Vest",
"Padded Vest",
"Fishscale Gauntlets",
"Scare Mask",
"Battered Helm",
"Serrated Arrow Quiver",
"Coral Ring",
"Gnarled Branch",
"Stone Axe",
"Stone Axe",
"Stone Axe",
"Chain Boots",
"Short Bow",
"Skinning Knife",
"Wrapped Mitts",
"Rusted Coif",
"Tribal Club",
"Copper Sword",
"Paua Ring",
"Darkwood Sceptre",
"Rotted Round Shield",
"Spiked Bundle",
"Corroded Tower Shield",
"Chestplate",
"Wrapped Boots",
"Leatherscale Boots",
"Large Life Flask",
"Large Mana Flask",
"Jade Hatchet",
"Goat's Horn",
"Jade Amulet",
"Lapis Amulet",
"Amber Amulet",
"Sharktooth Claw",
"Chain Gloves",
"Cone Helmet",
"Plank Kite Shield",
"Whalebone Rapier",
"Chainmail Tunic",
"Light Brigandine",
"Iron Circlet",
"Sapphire Ring",
"Pine Buckler",
"Tribal Maul",
"Longsword",
"Oiled Vest",
"Strapped Leather",
"Steel Greaves",
"Velvet Slippers",
"Long Bow",
"Goathide Gloves",
"Fire Arrow Quiver",
"Yew Spirit Shield",
"Primitive Staff",
"Jade Chopper",
"Heavy Belt",
"Leather Belt",
"Tricorne",
"Plague Mask",
"Small Hybrid Flask",
"Spiked Club",
"Sabre",
"Carving Knife",
"Bronze Sceptre",
"Silken Vest",
"Plated Gauntlets",
"Boarding Axe",
"Rawhide Tower Shield",
"Goathide Boots",
"Awl",
"Velvet Gloves",
"Soldier Helmet",
"Greater Life Flask",
"Greater Mana Flask",
"Topaz Ring",
"Driftwood Spiked Shield",
"Fir Round Shield",
"Battered Foil",
"Mallet",
"Bastard Sword",
"Carved Wand",
"Ringmail Boots",
"Sallet",
"Linden Kite Shield",
"Woodsplitter",
"Iron Staff",
"Composite Bow",
"Sharktooth Arrow Quiver",
"Gold Amulet",
"Stiletto",
"Ironscale Gauntlets",
"Stone Hammer",
"Broad Sword",
"Quartz Sceptre",
"Bone Spirit Shield",
"Strapped Boots",
"Strapped Mitts",
"Cleaver",
"Ruby Ring",
"Painted Buckler",
"Ringmail Coat",
"Buckskin Tunic",
"Scale Doublet",
"Copper Plate",
"Cat's Paw",
"Iron Mask",
"Torture Cage",
"Cedar Tower Shield",
"Basket Rapier",
"Sledgehammer",
"Two-Handed Sword",
"Scholar's Robe",
"Padded Jacket",
"Ironscale Boots",
"Recurve Bow",
"Barbute Helmet",
"Grand Life Flask",
"Grand Mana Flask",
"Long Staff",
"Poleaxe",
"Quartz Wand",
"Ringmail Gloves",
"Turquoise Amulet",
"Citrine Amulet",
"Agate Amulet",
"Studded Belt",
"Cloth Belt",
"Leather Hood",
"Medium Hybrid Flask",
"War Hammer",
"War Sword",
"Feathered Arrow Quiver",
"Gold Ring",
"Two-Stone Ring",
"Two-Stone Ring",
"Two-Stone Ring",
"Boot Knife",
"Iron Sceptre",
"Studded Round Shield",
"Alloyed Spiked Shield",
"Reinforced Kite Shield",
"Calling Wand",
"Infantry Brigandine",
"War Plate",
"Chainmail Doublet",
"Deerskin Gloves",
"Broad Axe",
"Oiled Coat",
"Silk Slippers",
"Deerskin Boots",
"Blinder",
"Great Helmet",
"Jagged Foil",
"Jagged Maul",
"Etched Greatsword",
"Plated Greaves",
"Bone Bow",
"Bronze Gauntlets",
"Visored Sallet",
"Hammered Buckler",
"Tarnished Spirit Shield",
"Double Axe",
"Coiled Staff",
"Giant Life Flask",
"Giant Mana Flask",
"Bladed Mace",
"Ancient Sword",
"Copper Kris",
"Ochre Sceptre",
"Copper Tower Shield",
"Spiraled Wand",
"Onyx Amulet",
"Silken Garb",
"Wild Leather",
"Silk Gloves",
"Arming Axe",
"Penetrating Arrow Quiver",
"Diamond Ring",
"Moonstone Ring",
"Timeworn Claw",
"Tribal Circlet",
"Close Helmet",
"Antique Rapier",
"Clasped Boots",
"Bronzescale Gauntlets",
"Scarlet Round Shield",
"Burnished Spiked Shield",
"Layered Kite Shield",
"Brass Maul",
"Ornate Sword",
"Full Leather",
"Full Plate",
"Full Ringmail",
"Full Scale Armour",
"Scarlet Raiment",
"Mage's Vestment",
"Mesh Boots",
"Royal Bow",
"Festival Mask",
"Ceremonial Mace",
"Elegant Sword",
"Skean",
"Ritual Sceptre",
"Jingling Spirit Shield",
"Royal Staff",
"Gilded Axe",
"Decorative Axe",
"War Buckler",
"Bronzescale Boots",
"Sparkling Claw",
"Flaying Knife",
"Wolf Pelt",
"Large Hybrid Flask",
"Colossal Life Flask",
"Colossal Mana Flask",
"Reinforced Tower Shield",
"Elegant Foil",
"Sage Wand",
"Clasped Mitts",
"Crusader Helmet",
"Blunt Arrow Quiver",
"Full Chainmail",
"Silk Robe",
"Arena Plate",
"Waxed Garb",
"Sun Leather",
"Soldier's Brigandine",
"Scholar Boots",
"Death Bow",
"Mesh Gloves",
"Dream Mace",
"Dusk Blade",
"Imp Dagger",
"Shadow Sceptre",
"Fright Maul",
"Spectral Sword",
"Reinforced Greaves",
"Nubuck Gloves",
"Gilded Sallet",
"Spectral Axe",
"Splendid Round Shield",
"Ornate Spiked Shield",
"Brass Spirit Shield",
"Shadow Axe",
"Vile Staff",
"Shackled Boots",
"Nubuck Boots",
"Fright Claw",
"Bone Circlet",
"Wyrm Mace",
"Hook Sword",
"Ceremonial Kite Shield",
"Gilded Buckler",
"Thorn Rapier",
"Morning Star",
"Pagan Wand",
"Thief's Garb",
"Cabalist Regalia",
"Bone Armour",
"Holy Chainmail",
"Lordly Plate",
"Field Lamellar",
"Grove Bow",
"Steel Gauntlets",
"Golden Mask",
"Gladiator Helmet",
"Etched Hatchet",
"Petrified Club",
"Variscite Blade",
"Grinning Fetish",
"Painted Tower Shield",
"Curved Blade",
"Faun's Horn",
"Riveted Boots",
"Steelscale Boots",
"Reflex Bow",
"Double Claw",
"Prong Dagger",
"Embroidered Gloves",
"Steelscale Gauntlets",
"Trapper Mitts",
"Secutor Helm",
"Sacred Life Flask",
"Sacred Mana Flask",
"Jasper Axe",
"Two-Point Arrow Quiver",
"Horned Sceptre",
"Crescent Staff",
"Smallsword",
"Dagger Axe",
"Totemic Maul",
"Butcher Sword",
"Eelskin Tunic",
"Sage's Robe",
"Bronze Plate",
"Antique Greaves",
"Thresher Claw",
"Riveted Gloves",
"Aventail Helmet",
"Walnut Spirit Shield",
"Woodful Staff",
"Wyrmbone Rapier",
"Jasper Chopper",
"Wyrmscale Doublet",
"Satin Slippers",
"Decurve Bow",
"Eelskin Gloves",
"Raven Mask",
"Barbed Club",
"Cutlass",
"Amethyst Ring",
"Butcher Knife",
"Sekhem",
"Oak Buckler",
"Latticed Ringmail",
"Eelskin Boots",
"Antique Gauntlets",
"Lunaris Circlet",
"Tomahawk",
"Buckskin Tower Shield",
"Maple Round Shield",
"Redwood Spiked Shield",
"Quilted Jacket",
"Zealot Boots",
"Gouger",
"Reaver Helmet",
"Colossal Hybrid Flask",
"Spike-Point Arrow Quiver",
"Etched Kite Shield",
"Burnished Foil",
"Great Mallet",
"Footman Sword",
"Engraved Wand",
"Silken Wrap",
"Frontier Leather",
"Battle Plate",
"Trapper Boots",
"Compound Bow",
"Poignard",
"Satin Gloves",
"Hunter Hood",
"Rock Breaker",
"Baselard",
"Crystal Sceptre",
"Ivory Spirit Shield",
"Timber Axe",
"Military Staff",
"Hussar Brigandine",
"Serpentscale Boots",
"Hallowed Life Flask",
"Hallowed Mana Flask",
"Wrist Chopper",
"Enameled Buckler",
"Crusader Chainmail",
"Tiger's Paw",
"Zealot Gloves",
"Serpentscale Gauntlets",
"Fencer Helm",
"Mahogany Tower Shield",
"Estoc",
"Sleek Coat",
"Sharkskin Boots",
"Samite Slippers",
"Sniper Bow",
"Zealot Helmet",
"Battle Hammer",
"Battle Sword",
"Boot Blade",
"Lead Sceptre",
"Steelhead",
"Highland Blade",
"Sun Plate",
"Glorious Leather",
"Conjurer's Vestment",
"Sharkskin Gloves",
"Sharkskin Gloves",
"Ambush Mitts",
"Callous Mask",
"War Axe",
"Blazing Arrow Quiver",
"Unset Ring",
"Ancient Spirit Shield",
"Spiked Round Shield",
"Compound Spiked Shield",
"Quarterstaff",
"Headsman Axe",
"Crystal Wand",
"Full Wyrmscale",
"Ancient Greaves",
"Gut Ripper",
"Corrugated Buckler",
"Steel Kite Shield",
"Serrated Foil",
"Ornate Ringmail",
"Ambush Boots",
"Ivory Bow",
"Samite Gloves",
"Ancient Gauntlets",
"Noble Tricorne",
"Flanged Mace",
"Elder Sword",
"Golden Kris",
"Blood Sceptre",
"Bronze Tower Shield",
"Crimson Raiment",
"Steel Circlet",
"Siege Helmet",
"Chest Splitter",
"Spiny Maul",
"Engraved Greatsword",
"Spidersilk Robe",
"Coronal Leather",
"Colosseum Plate",
"Soldier Boots",
"Prehistoric Claw",
"Wyrmscale Gauntlets",
"Broadhead Arrow Quiver",
"Chiming Spirit Shield",
"Crimson Round Shield",
"Polished Spiked Shield",
"Primeval Rapier",
"Labrys",
"Coiled Wand",
"Serpentine Staff",
"Commander's Brigandine",
"Highborn Bow",
"Carnal Mitts",
"Sacred Hybrid Flask",
"Sanctified Life Flask",
"Sanctified Mana Flask",
"Ornate Mace",
"Graceful Sword",
"Royal Skean",
"Royal Sceptre",
"Laminated Kite Shield",
"Battle Buckler",
"Convening Wand",
"Chain Hauberk",
"Wyrmscale Boots",
"Trisula",
"Soldier Gloves",
"Lacquered Helmet",
"Ceremonial Axe",
"Girded Tower Shield",
"Plated Maul",
"Tiger Sword",
"Lacquered Garb",
"Noble Claw",
"Regicide Mask",
"Highborn Staff",
"Fancy Foil",
"Noble Axe",
"Destroyer Regalia",
"Majestic Plate",
"Cutthroat's Garb",
"Conjurer Boots",
"Decimation Bow",
"Goliath Gauntlets",
"Great Crown",
"Phantom Mace",
"Twilight Blade",
"Fiend Dagger",
"Abyssal Sceptre",
"Thorium Spirit Shield",
"Omen Wand",
"Battle Lamellar",
"Goliath Greaves",
"Shagreen Gloves",
"Necromancer Circlet",
"Wraith Axe",
"Golden Buckler",
"Baroque Round Shield",
"Sovereign Spiked Shield",
"Dread Maul",
"Wraith Sword",
"Devout Chainmail",
"Shagreen Boots",
"Carnal Boots",
"Eagle Claw",
"Conjurer Gloves",
"Samnite Helmet",
"Ursine Pelt",
"Dragon Mace",
"Grappler",
"Vile Arrow Quiver",
"Stag Sceptre",
"Angelic Kite Shield",
"Crested Tower Shield",
"Apex Rapier",
"Abyssal Axe",
"Heathen Wand",
"Foul Staff",
"Savant's Robe",
"Golden Plate",
"Sharkskin Tunic",
"Crypt Armour",
"Thicket Bow",
"Gutting Knife",
"Engraved Hatchet",
"Ancestral Club",
"Gemstone Sword",
"Karui Sceptre",
"Lacewood Spirit Shield",
"Solar Maul",
"Lithe Blade",
"Demon's Horn",
"Dragonscale Doublet",
"Steelwood Bow",
"Twin Claw",
"Legion Gloves",
"Harlequin Mask",
"Karui Axe",
"Ironwood Buckler",
"Moon Staff",
"Courtesan Sword",
"Karui Maul",
"Headman's Sword",
"Loricated Ringmail",
"Legion Boots",
"Citadel Bow",
"Great White Claw",
"Assassin's Mitts",
"Fluted Bascinet",
"Magistrate Crown",
"Tenderizer",
"Corsair Sword",
"Slaughter Knife",
"Tyrant's Sekhem",
"Shagreen Tower Shield",
"Teak Round Shield",
"Alder Spiked Shield",
"Primordial Staff",
"Dragonbone Rapier",
"Karui Chopper",
"Necromancer Silks",
"Crusader Plate",
"Destiny Leather",
"Sentinel Jacket",
"Hydrascale Boots",
"Hydrascale Gauntlets",
"Solaris Circlet",
"Siege Axe",
"Fossilised Spirit Shield",
"Branded Kite Shield",
"Talon Axe",
"Colossus Mallet",
"Reaver Sword",
"Imbued Wand",
"Desert Brigandine",
"Ranger Bow",
"Throat Stabber",
"Ambusher",
"Arcanist Gloves",
"Silken Hood",
"Ezomyte Burgonet",
"Hallowed Hybrid Flask",
"Divine Life Flask",
"Divine Mana Flask",
"Gavel",
"Gladius",
"Opal Sceptre",
"Lacquered Buckler",
"Tempered Foil",
"Sundering Axe",
"Ezomyte Staff",
"Conquest Chainmail",
"Arcanist Slippers",
"Reaver Axe",
"Heavy Arrow Quiver",
"Ebony Tower Shield",
"Piledriver",
"Ezomyte Blade",
"Astral Plate",
"Exquisite Leather",
"Varnished Coat",
"Occultist's Vestment",
"Vaal Greaves",
"Stealth Boots",
"Assassin Bow",
"Hellion's Paw",
"Stealth Gloves",
"Vaal Mask",
"Legion Hammer",
"Legion Sword",
"Ezomyte Dagger",
"Platinum Sceptre",
"Spiny Round Shield",
"Vaal Spirit Shield",
"Ezomyte Spiked Shield",
"Champion Kite Shield",
"Lathi",
"Pecoraro",
"Ezomyte Axe",
"Opal Wand",
"Full Dragonscale",
"Assassin's Boots",
"Vaal Gauntlets",
"Prophet Crown",
"Pig-Faced Bascinet",
"Butcher Axe",
"Vaal Buckler",
"Meatgrinder",
"Vaal Greatsword",
"Elegant Ringmail",
"Crusader Boots",
"Spine Bow",
"Eye Gouger",
"Sinner Tricorne",
"Pernach",
"Vaal Blade",
"Platinum Kris",
"Vaal Sceptre",
"Ezomyte Tower Shield",
"Spiraled Foil",
"Vaal Axe",
"Maelström Staff",
"Zodiac Leather",
"Widowsilk Robe",
"Gladiator Plate",
"Blood Raiment",
"Dragonscale Boots",
"Mind Cage",
"Royal Burgonet",
"Eternal Life Flask",
"Eternal Mana Flask",
"Vaal Hatchet",
"Harmonic Spirit Shield",
"Mosaic Kite Shield",
"Imperial Maul",
"Lion Sword",
"Tornado Wand"
    ]